### ISSUE TITLE
Default USSD code based on provider

### ISSUE THREAD

**Issue by mueller-ma** [mueller-ma/PrepaidBalance#10]
Not `#100*` for every provider.

**Comment by mueller-ma** [comment]
@FestplattenSchnitzel What's the MCC and MNC of your provider? It's shown in the settings now.

**Comment by FestplattenSchnitzel** [comment]
```
MMC: 262
MNC: 2
```

Matches according to [Wikipedia](https://en.wikipedia.org/wiki/Mobile_Network_Codes_in_ITU_region_2xx_(Europe)#Germany_%E2%80%93_DE).
