### ISSUE TITLE
downgrade android version

### ISSUE THREAD

**Issue by OmlineEditor** [mueller-ma/PrepaidBalance#100]
now the minimum version for work is android 8. I ask you to downgrade the android version to at least version 6. there are a lot of people who use old devices, including me.

I am sure it is possible to do this because the program is very simple and does not strictly require the presence of android 8. I think even on android 4 you can run your program.

**Comment by mueller-ma** [comment]
The [API to make USSD requests has been added in Android 8](https://developer.android.com/reference/android/telephony/TelephonyManager#sendUssdRequest(java.lang.String,%20android.telephony.TelephonyManager.UssdResponseCallback,%20android.os.Handler)) thus I cannot lower the minimum version.
