### ISSUE TITLE
US - Tmobile response

### ISSUE THREAD

**Issue by cellfdroid** [mueller-ma/PrepaidBalance#106]
Currently Tmobile US response after parsing show balance as month(eg 8) instead of actual balance.

Here is full response if it helps:

Current plan active until 08/10/2022 and will renew for $15.00. Account Balance $15.00. Add money by dialing *233 or redeem a refill card.

**Comment by mueller-ma** [comment]
The string could be "Current plan active until 08/10/2022 and will renew for $15.00. Account Balance $12.34. Add money by dialing *233 or redeem a refill card." as well and then the balance is `12.34`, right?

**Comment by cellfdroid** [comment]
Right, 12.34 is balance in this case.
