### ISSUE TITLE
App doesn't work with my device/provider

### ISSUE THREAD

**Issue by cyclingcat** [mueller-ma/PrepaidBalance#107]
Hi there,

thank you for this app, I stumbled upon it on F-Droid and I have been looking for something like this for some time. However, it doesn't work with my device, so I hope, it's easily fixable (Version 1.8 from F-Droid).

**How to reproduce**
- I entered the USSD code of my provider in the settings (*106#, Lidl Connect, Germany, Vodafone network)
- I swiped down as requested. An error message appears: "Auslesen des Guthabens fehlgeschlagen. Dieser Dienst steht in Ihrem Tarif nicht zur Verfügung". However, if I dial the above mentioned USSD code manually, my balance is shown correctly. See the screenshot:

![Screenshot](https://user-images.githubusercontent.com/32601012/181166381-6f92b7a3-ed85-4edc-9119-9d02c530ef76.jpg)

**Device (please complete the following information):**
 - Device: Realme 8 Pro, most recent firmware. Both SIM slots used, but configured to use a dedicated SIM (this Lidl Connect one) for outgoing phone calls
 - Android version: 12
 - MCC: 262
 - MNC: 7

**Comment by mueller-ma** [comment]
Can you remove the second SIM card and try it again to make sure the app is using the correct SIM?

**Comment by cyclingcat** [comment]
Hi there,

just tried it out (I replaces the **second** SIM card with another one) and now it works. So it could indeed be the second SIM card which caused the problem although I want to check the first SIM card with this app and this one is always configured as default SIM card for outgoing phone calls (I use the second one only for data, never for phone calls).

Let me know if you want me to test anything - I've got enough SIM cards here (from different German providers in all three German networks) and three phones with Android 5.1, 9 and 12.

The cycling cat

**Comment by mueller-ma** [comment]
Ok, so this issue should be fixed when implementing #96, but I'm currently not working on it.

**Comment by cyclingcat** [comment]
For me it's currently ok now as the current setting is my main one. Feel free to close this issue.

The cycling cat
