### ISSUE TITLE
Failed to request ussd code

### ISSUE THREAD

**Issue by stop5** [mueller-ma/PrepaidBalance#11]
**Describe the bug**
Failed to request USSD Code

**To Reproduce**
1. Set *101# for my ussd code
2. pull down screen
3. a toast appears with the message "Failed to request USSD Code"

**Expected behavior**
that my current balance is displayed

**Screenshots**
![IMG_20210613_174640.jpg](https://user-images.githubusercontent.com/6901125/121814057-5be36f00-cc6f-11eb-94b5-d5de3cea25f3.jpg)

**Device (please complete the following information):**
 - Device: Oneplus 7 Pro
 - Android version: 11
 - MCC and MNC (Shown in settings): 262 07
All permissions are granted.

**Comment by mueller-ma** [comment]
What happens when you dial *101# in your dialer?

**Comment by stop5** [comment]
A spinner is opened and after that a window is opening:
Nachricht von o2
Ihr Guthaben beträgt: 15,67€.

**Comment by mueller-ma** [comment]
This error is displayed when the app doesn't receive an response at all. I'm not sure what can cause this issue.

Can you just try it again?

**Comment by kaitou1412** [comment]
I got this "Failed to request USSD code" error also,
And sometimes it showed "Unable to get balance from response"

USSD code: *123#

Results when queried manualy:

![ussd](https://user-images.githubusercontent.com/5919461/143172912-6527c51e-4d31-4e9b-841e-b9f8ea0d01cf.png)

How to debug, BTW?

**Comment by kaitou1412** [comment]
![image](https://user-images.githubusercontent.com/5919461/143173338-e320028b-079a-46a0-b088-cd6b42f4a881.png)

**Comment by mueller-ma** [comment]
> I got this "Failed to request USSD code" error also,

This means that there's a network issue.

> And sometimes it showed "Unable to get balance from response"

Can you paste the text from the screenshot as text here? Then I can add a parser for it, but it may select the wrong "Rp" value.
Is there maybe another USSD code that only shows the balance?

**Comment by kaitou1412** [comment]
Maybe you can parse only the first portion "Pulsa Rp 6499"

because many times the content after that change according to the cell operator

currently it's the only USSD code I know to show the balance

BTW have you ever try this application <https://play.google.com/store/apps/details?id=com.mdnsoft.ussddualwidget&hl=en&gl=US> ?

I remember it can adjust the parsing manually

**Comment by mueller-ma** [comment]
I added your USSD response and it's parsed correctly: https://github.com/mueller-ma/PrepaidBalance/commit/c18522d7fffc3b0255d60a7f33b5d4c094a3968a

**Comment by mueller-ma** [comment]
I'm going to add some more debugging messages to the app to locate this issue.

**Comment by kaitou1412** [comment]
thank you..
please let me know when I can test it again

**Comment by mueller-ma** [comment]
Can you check "Last USSD response" in the settings in version 1.2?

**Comment by kaitou1412** [comment]
Thank you..
Here is the response:
Last request failed with code-1

**Comment by mueller-ma** [comment]
`-1` means:

> Failed code returned when the mobile network has failed to complete a USSD request. 

https://developer.android.com/reference/kotlin/android/telephony/TelephonyManager?hl=en#ussd_return_failure

AFAIK this issue is outside of the app. Maybe you can try a different USSD code?

**Comment by abdigemechufufa** [comment]
Hello mueller-ma i love this app and i am note good enough at kotlin and my own project is java so can i get your project with java code? please do for java and make a branch for it. Thanks

**Comment by mueller-ma** [comment]
Hi,
I'm not going to make a second version of this app in Java. A Java version would use the same Java classes as it currently does, so feel free to check their docs.
