### ISSUE TITLE
USSD Sub-Menu

### ISSUE THREAD

**Issue by tgxn** [mueller-ma/PrepaidBalance#115]
My Provider - Boost Mobile Australia; 505 1
Only supports accessing balance using `#100#` and then choosing option `3` from the USSD menu.

Would it be possible to support this sub-menu configuration within this app?

Thanks!

**Comment by mueller-ma** [comment]
USSD menu aren't supported by the Android API that I use here: https://issuetracker.google.com/issues/69251738

Maybe Google changes this, but I cannot.
