### ISSUE TITLE
Select sim card for ussd code

### ISSUE THREAD

**Issue by adonetgithub** [mueller-ma/PrepaidBalance#124]
De app chooses the wrong SIM card for checking the prepaid Balance using the ussd code.

**To Reproduce**
Install the app and enter the ussd code that is needed to check the prepaid Balance.
If there are two SIM cards the app will give an error when reading the prepaid Balance is triggered 
If I remove the SIM card that is not supported with USSD than the app will choose the right SIM card. If I enter the Second SIM card again then the app chooses the wrong SIM card again.

**Expected behavior**
I would like that we app gives you a choice for the sim card to use the ussd code with.

**Screenshots**
I don't have a screenshot.

**Device (please complete the following information):**
 - Device: Nokia X10
 - Android version: 12
 - MCC and MNC (Shown in settings): 
 - MCC: 204
 - MNC: 16 should be 8

**Additional context**
I tried to install the app with only the right SIM card in the phone. That works until I put the second SIM card in the phone again.

**Comment by Devendra34** [comment]
> In this issue I'd track _true_ multi sim support, i.e. set different USSD codes for each sim card. You can implement #124 by adding a simple setting to select one sim card.
Hi @mueller-ma, as discussed before, would you like to assign this #124 to me? I'll start the implementation once you give a confirmation. 
Thanks!

**Comment by Devendra34** [comment]
Thanks for assigning. 
Coming to the UI interaction part for sim card selection, I was thinking since we already have alert dialog kind of setup on the swipe event, we can go ahead with the same approach by showing a list of sim cards, from which whether the user selects we can call the chechBalance method with selected sim. 
Does that looks good to you?

**Comment by Devendra34** [comment]
Hi @mueller-ma,
Let me raise a PR with the approach discussed above.
Feel free to ping me if there is anything that needs to be changed.
I'm still open for your feedback on the same. Please respond whenever you can.
Thanks!

**Comment by adonetgithub** [comment]
> Thanks for assigning. Coming to the UI interaction part for sim card selection, I was thinking since we already have alert dialog kind of setup on the swipe event, we can go ahead with the same approach by showing a list of sim cards, from which whether the user selects we can call the checkBalance method with selected sim. Does that looks good to you?

I think that that should be usable. Select the SIM-card from a drop-down menu and enter the USSD code to use with that SIMcard.

If that is working you could think for even more functions:

It  would be useful to select the SIM-card to use with the USSD code, add the posibility  to check different USSD codes for different functions (e.g. a USSD code for balance for making a phonecall and a second USSD code for checking balance for internet access).
And sometimes both SIM cards offer USSD functions. In that case it would be nice if you can have both SIM cards checked, for one or both functions.

**Comment by Devendra34** [comment]
Okay @adonetgithub.
Lets do everything step-by-step
To begin with let me raise a PR with my current implementation and see how does that work from the demo.
Before adding any new functionalities, lets see if it first solves the existing issue.
Thanks!

**Comment by adonetgithub** [comment]
The new version I installed from F-droid works. Thanks a lot. One thing doesn't. In settings under troubleshooting the provider details aren't updated when selecting another SIM card. But this doesn't affect functionality.

**Comment by mueller-ma** [comment]
I changed the string to "Default provider details". The API I use the get MCC and MNC can only return the values of the default sim card.
