### ISSUE TITLE
Update dependencies 

### ISSUE THREAD

**Issue by mueller-ma** [mueller-ma/PrepaidBalance#126]
1. Pick one dependency from https://github.com/mueller-ma/PrepaidBalance/pulls?q=is%3Apr+is%3Aopen+label%3Adependencies
2. Fix all build issues and warnings.
3. Push fixes and bumped version to a new branch.
4. Open a pull request.

**Comment by snaik20** [comment]
Created https://github.com/mueller-ma/PrepaidBalance/pull/128 to upgrade the Gradle version. Please take a look.

**Comment by snaik20** [comment]
Created https://github.com/mueller-ma/PrepaidBalance/pull/130 to upgrade AppCompat version. Also updated targetSdkVersion

**Comment by snaik20** [comment]
Created https://github.com/mueller-ma/PrepaidBalance/pull/131 to upgrade the core-ktx version.
