### ISSUE TITLE
balance expiry date notification

### ISSUE THREAD

**Issue by nutpantz** [mueller-ma/PrepaidBalance#13]
it would be great if the app also got the expiry date and had the option for a notification for a set time before the expiry

 Preferably a user set notification days weeks and repeating for the notification

**Comment by Vetgans** [comment]
Implementing (repeating) notifications is probably a relatively big step for this app. Displaying the expiration date however would be a really nice addition, and probably easier to accomplish.

**Comment by mueller-ma** [comment]
How does your USSD code response look like? Probably the most difficult step here is to extract the date from the text.

**Comment by Vetgans** [comment]
The USSD code (*101#) response (from Vodafone NL) looks like this, in Dutch:
```
Bericht van Vodafone

Je Prepaid tegoed is euro 63.27. Geldig tot 23/11/2021. Nooit zonder tegoed? Kijk op vodafone.nl/opwaarderen voor Overal Opwaarderen.
```
So the expiration date is formulated as 23/11/2021. Probably the 2 slashes '/' can help to distinguish the date? Or the '/20**'-part?
I don't have access to other carriers to test whether this is a standardized format for responses to USSD codes.

**Comment by mueller-ma** [comment]
The string 01/02/2022 could respresent the 1st February or the 2nd Janaury 2022. In addition to the format the parses must also guess the locale of the USSD response, which seems quite hard to implement this.

However I could show the full USSD response after a manual query. This would show the expiration date as well.
