### ISSUE TITLE
custom balance refresh rate

### ISSUE THREAD

**Issue by nutpantz** [mueller-ma/PrepaidBalance#135]
It appears now that the app checks twice a day if you have periodic check enabled, it would be nice if the user could set the refresh time 4x a day to maybe once every 2 weeks.

**Comment by webcaptcha** [comment]
+1 from my side for this request

**Comment by mueller-ma** [comment]
Implemented in https://github.com/mueller-ma/PrepaidBalance/commit/5159090ab64c50466e9631078ea4792a4074424d
