### ISSUE TITLE
Unable to get balance from response - Sunrise Switzerland

### ISSUE THREAD

**Issue by studied-sermon-gender** [mueller-ma/PrepaidBalance#136]
Hey
I get the error message "Unabe to get balance from response" when I try to use the app. I entered the right USSD Code (*121#). I assume that my provider isn't in the parser yet. The details are as following:

Cellphone provider: Sunrise
Country: Switzerland
USSD Code: *121#
MCC/MNC: 228/2
Answer when dialing USSD code: Ihr Guthaben beträgt CHF 24.50.

I hope this helps. If anymore details are needed, don't hesitate to ask.
Best regards

**Comment by studied-sermon-gender** [comment]
Hey, it still doesn't work. I'm not a developer so I have no idea why. I inspected the commit and saw that in there the answer is written as "Ihr Guthaben beträgt CHF 12.34", when in reality, so when I type *121#, the answer is "Ihr Guthaben beträgt CHF 12.34.", so with a period at the end. Maybe this is the issue?

**Comment by studied-sermon-gender** [comment]
I just updated and it still doesn't work. I have no idea what the issue might be.

**Comment by mueller-ma** [comment]
Can you make sure that you selected the correct sim card? Is the error still "Unabe to get balance from response"?

**Comment by studied-sermon-gender** [comment]
Yes, I only have one sim card in my phone and that one is selected. The error message is as following: "Unable to get balance from response: Ihr Guthaben beträgt CHF 12.34."

**Comment by mueller-ma** [comment]
Can you capture the app log via adb? There should be a line containing `onReceiveUssdResponse(<your response here>)`. Maybe there's an issue with umlaute?

**Comment by mueller-ma** [comment]
>  (Without any closing bracket at the end)

Ok, so maybe there's some invisible character at the line ending. I try to remove invisible characters.

**Comment by mueller-ma** [comment]
Version 1.14 will replace any char that is not one of `A-Za-z0-9.:$£` by a regular whitespace: https://github.com/mueller-ma/PrepaidBalance/commit/08859faddeb92dd27f9a0c0e2a22ae2200cef6a9

**Comment by studied-sermon-gender** [comment]
Thanks, it works now!
Best regards
