### ISSUE TITLE
Support more than one USSD code

### ISSUE THREAD

**Issue by webcaptcha** [mueller-ma/PrepaidBalance#138]
**Is your feature request related to a problem? Please describe.**
My operator provides two separate codes. One is using to get balance in $$$ (*111#), the second one shows me the number of MB is left (*121#)
There is no way to combine it.

**Describe the solution you'd like**
Something like +sign (icon) to add one more USSD code

**Describe alternatives you've considered**
Just finding your app and find it pretty useful.

**Additional context**
Well, that's all I think

**Comment by OmlineEditor** [comment]
look at the picture at the end of the discussion in this request https://github.com/mueller-ma/PrepaidBalance/issues/96  I think this is how you can support multiple sim cards and multiple requests

**Comment by webcaptcha** [comment]
Sorry for some delay. I don't have two SIMs card on my device. Just phone with one SIM card. Neither E-SIM or additional physical SIM card.

But I do have two different USSD code. One code is for checking balance in $. Second one is for checking MB left

**Comment by OmlineEditor** [comment]
> Sorry for some delay. I don't have two SIMs card on my device. Just phone with one SIM card. Neither E-SIM or additional physical SIM card.
> 
> But I do have two different USSD code. One code is for checking balance in $. Second one is for checking MB left

we already have the opportunity to ask for the code, we need to change the interface and change the type of settings so that we can ask for different codes. check out the picture here at the end https://github.com/mueller-ma/PrepaidBalance/issues/96

**Comment by webcaptcha** [comment]
Looks good. I will be waiting as much as it needed. I find this small application super useful.

**Comment by OmlineEditor** [comment]
why is the ticket closed?

**Comment by mueller-ma** [comment]
I don't have the resources to implement this and no-one else opened a PR.

**Comment by OmlineEditor** [comment]
perhaps in the future someone will do this functionality for you, or you will do it when the time comes. it is illogical to close a ticket if there is no time to implement it or no one has responded to do it yet
