### ISSUE TITLE
F-Droid says: "No versions compatible with device"

### ISSUE THREAD

**Issue by mikabak** [mueller-ma/PrepaidBalance#14]
**Describe the bug**

**To Reproduce**
1. Open F-Droid
2. Search for "Prepaid Balance"
3. F-Droid does not display "Install" button"
4. Scroll down to bottom to see the text "No versions compatible with device"

**Expected behavior**
I would expect this app to work on my phone ;)

**Device (please complete the following information):**
 - Device: Samsung Galaxy SII (GT-I9100)
 - Android version: 7.1.2 (LineageOS 14.1)
 - MCC and MNC (Shown in settings): 

**Additional context**
Mostly out of curiosity is my device incompatible or is the version of Android too old?
Thanks!

**Comment by mueller-ma** [comment]
The required Api was introduced with Android 8.
