### ISSUE TITLE
support Android 6+

### ISSUE THREAD

**Issue by nutpantz** [mueller-ma/PrepaidBalance#144]
A lot of older Android devices never got updates past Android 6 or 7 either from the oem or from custom ROM developers fire many reasons, but many many of these older devices are being used by those with limited funds like the elderly and students. Also many of those people are also on pre paid plans.. 

Is there any reason why the app could not be made compatible with Android 6 and newer? Or at least Android 7 or 7.1

**Comment by mueller-ma** [comment]
The [API to make USSD requests has been added in Android 8](https://developer.android.com/reference/android/telephony/TelephonyManager#sendUssdRequest(java.lang.String,%20android.telephony.TelephonyManager.UssdResponseCallback,%20android.os.Handler)), thus I cannot lower the minimum version.

**Comment by OmlineEditor** [comment]
I have an old phone on android 2.3 version there is another program (similar to yours) and it can make a balance request.
I'm sure there is a way to make a balance request even for android version 6.
can you look for that way?

**Comment by mueller-ma** [comment]
I've seen solutions for this, but they are all quite hacky and something I don't want to include in this app. It's a source of endless issues and debugging.
