### ISSUE TITLE
Parsing of balance for O2 (UK) fails

### ISSUE THREAD

**Issue by SingingDwarf** [mueller-ma/PrepaidBalance#145]
**Describe the bug**
The balance for O2 within the UK is not parsed correctly.

**To Reproduce**
Run USSD.
Balance is reported incorrectly.

**Expected behavior**
Balance is parsed correctly.

**Screenshots**
![Screenshot_2022-10-13-08-48-40-495_com github muellerma prepaidbalance](https://user-images.githubusercontent.com/5740895/195536365-381fe349-8de0-4538-b5cd-a918036ae1ab.jpg)

**Device (please complete the following information):**
Xiaomi Note 9

MCC: 234
MNC: 10

Balance is reported as 2.00 for the response:

O2: Your balance is £9.58. Text BALANCE free to 20202 to check your remaining tariff and Bolt On allowances.

**Additional context**

**Comment by mueller-ma** [comment]
Will be fixed in 1.13.
