### ISSUE TITLE
battery usage issue

### ISSUE THREAD

**Issue by nutpantz** [mueller-ma/PrepaidBalance#149]
I recently added this to my s7 edge running Android 11.
The phone is for emergency use only so sits for days at a time.
 Before the app the device was using  0.21% an hour after i installed and set up prepaid balance app it went up to 1.02% an hour. Which is 5x more, which is a bit much for 2 text a day.i uninstalled the app and it went back down to 0.2% an hour.

**Comment by mueller-ma** [comment]
A custom refresh rate is requested in #135 which will help to reduce battery usage. You can also disable automatic refreshes completely, so the app doesn't use battery when it's not opened.

**Comment by nutpantz** [comment]
I have just tested the app with no auto refreshes and it seems like battery usage is still very high 0.96% with the app installed and set up but no auto refresh or manual refresh in 12 hours. Without the app installed 0.26%. still the same device as before. It does nothing but sit there waiting for text messages or energy use. (Of which it had none so they did not take up battery usage)

**Comment by nutpantz** [comment]
> A custom refresh rate is requested in #135 which will help to reduce battery usage. You can also disable automatic refreshes completely, so the app doesn't use battery when it's not opened.

I have just tested the app with no auto refreshes and it seems like battery usage is still very high 0.96% with the app installed and set up but no auto refresh or manual refresh in 12 hours. Without the app installed 0.26%. still the same device as before. It does nothing but sit there waiting for text messages or energy use. (Of which it had none so they did not take up battery usage)
(Repost because i forgot to quote author)

**Comment by mueller-ma** [comment]
How much battery usage is attributed to the app, according to the battery usage overview in the Android settings?

**Comment by nutpantz** [comment]
Nothing shows up in there. Not the email apps that are running or prepaid. Just the system  usage. There are only 4 apps installed. Ex kernel, Proton mail, tutanota mail and prepaid.  It's a custom ROM so that feature might be broken. Ex kernel battery monitor is what i use to gauge how much battery an hour is being used.

**Comment by mueller-ma** [comment]
WorkManager, the go-to library for background tasks, might check from time to time if a task has to be run. On some devices I checked this app uses less than 1% battery per full charge.

I'm not aware of any solution for this. You could fork this app and remove WorkManager.
