### ISSUE TITLE
[Thailand] TrueMove-H

### ISSUE THREAD

**Issue by kowith337** [mueller-ma/PrepaidBalance#15]
**Cellphone provider and Country**
Carrier name: Truemove-H
Country: Thailand
MMC: 520
MNC: 65535 (but maybe `00` ?)

**Actual USSD answer**
```
คุณมี xx.yy บ. ถึง dd/mm/yyyy
```

**Additional notes**
The `*123` is use for refill balance with `*123*{cardnumber}#` pattern, but an  actual balance check number is `#123#`, the app said USSD code must begin with `*`, so this app will fail for this carrier.

**Comment by mueller-ma** [comment]
> MNC: 65535 (but maybe 00 ?)

Yes, seems to be 00: https://en.wikipedia.org/wiki/Mobile_Network_Codes_in_ITU_region_5xx_(Oceania)#Thailand_%E2%80%93_TH

How do you query your balance manually? With `*123`?

**Comment by kowith337** [comment]
Sorry, I've misunderstood about USSD and edited to correct answer.
The year format is BE year that +543 from CE year.

**Comment by mueller-ma** [comment]
Can you check 0.5 when it's on F-Droid?

**Comment by kowith337** [comment]
I've just fetch repo update and seems didn't get new updats today yet, can you have separate APK releases?

**Comment by mueller-ma** [comment]
I don't plan to distribute an apk of this app over GitHub.

**Comment by kowith337** [comment]
Already got updated now and it's work, Thanks.
