### ISSUE TITLE
with auto update failed attempts at ussd should retry

### ISSUE THREAD

**Issue by nutpantz** [mueller-ma/PrepaidBalance#155]
Right now when on auto update a failed attempt to getting the balance will leave an error in the notification window. Possibly even after a day and it updates.

On automatic The app should try a second time in 30 minutes after a failure and possibly try a third time, after which it should error out and give the time of the error. Then stop trying.
If it gets a  response it should clear the error from the notification area.

**Comment by mueller-ma** [comment]
Currently the background worker always signals success to work manager: https://github.com/mueller-ma/PrepaidBalance/blob/main/app/src/main/java/com/github/muellerma/prepaidbalance/work/CheckBalanceWorker.kt#L71

This should be fixed first, then a backoff policy can be added, so the fetch is retried automatically short after a failure.
