### ISSUE TITLE
Regex parsing  / Display only account balance 

### ISSUE THREAD

**Issue by bielej** [mueller-ma/PrepaidBalance#160]
**Is your feature request related to a problem? Please describe.**
My Provider adds many useless characters to the USSD response, which makes it cluttered. 

**Describe the solution you'd like**
I would like to be able to configure a regular expression to parse the USSD answer with. 

**Describe alternatives you've considered**
Automatically (probably using a regular expression) parse the repose to find the exact account balance - display only digits.

**Comment by mueller-ma** [comment]
>  Automatically (probably using a regular expression) parse the repose to find the exact account balance - display only digits.

Isn't this an exact description of the current behavior of the app? Several regex patterns are included in the app: https://github.com/mueller-ma/PrepaidBalance/blob/main/app/src/main/java/com/github/muellerma/prepaidbalance/utils/ResponseParser.kt#L10-L34

**Comment by bielej** [comment]
You're right - but still, it's hardcoded. I would be nice if the user could configure the pattern.

**Comment by mueller-ma** [comment]
Can you post a USSD response here? Then I can add a parser for that.

Adding a preference to enter a custom regex seems more work to me and hard to debug for the user.

**Comment by bielej** [comment]
```
Twoja oferta to nju na karte.
1.Stan konta glownego: 11.00 zl. Srodki wazne bezterminowo.
```
