### ISSUE TITLE
Tasker integration

### ISSUE THREAD

**Issue by bielej** [mueller-ma/PrepaidBalance#161]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like to have integration with Tasker.  
This would allow custom triggers for checking account balance.
Also, the response could be returned to Tasker for further processing (for purposes such as widgets, notifications etc.)

**Comment by juleskers** [comment]
Just in case anyone is interested in this, tasker seems to provide developer documentation on how to integrate apps with it:
https://tasker.joaoapps.com/developers.html 

Their preferred way is by including a tasker-provided dependency into one's app:
https://tasker.joaoapps.com/pluginslibrary.html

**Comment by mueller-ma** [comment]
https://github.com/mueller-ma/PrepaidBalance/issues/96#issuecomment-2460571668
