### ISSUE TITLE
Add support widget

### ISSUE THREAD

**Issue by xmha97** [mueller-ma/PrepaidBalance#164]
Please add support widget:

![Screenshot_2022-11-22-18-51-00-528_com.miui.home.jpg](https://user-images.githubusercontent.com/23485114/203386562-76eed964-1a28-49b5-9080-6c07b85011e2.jpg)

**Comment by OmlineEditor** [comment]
I ask you to make it possible to select the name of the SIM card in the widget and the unit of measurement of the balance, the user himself will be able to choose all this.

**Comment by xmha97** [comment]
Thanks 🙏
