### ISSUE TITLE
Support my operator

### ISSUE THREAD

**Issue by xmha97** [mueller-ma/PrepaidBalance#166]
Hi, please support my operator:

```
Credit 43240 IRR. WOW 0 IRR, till 9378/10/12.
Reply to activate:
1.42GB 106250T
2.5GB DATA 10000T
3.10GB 10Days 10000T
```

![IMG_20221125_190936_361.jpg](https://user-images.githubusercontent.com/23485114/204017998-3455e700-136a-4783-a343-ffcf98b69697.jpg)

**Comment by mueller-ma** [comment]
This kind of USSD code cannot be supported, see Readme:

> The USSD code to query the balance is "menu based", i.e. if you enter it in the dialer app, you get a menu. See https://github.com/mueller-ma/PrepaidBalance/issues/81#issuecomment-1131516634 for more details.
