### ISSUE TITLE
Don't try to check in airplane mode

### ISSUE THREAD

**Issue by markushub** [mueller-ma/PrepaidBalance#169]
**Is your feature request related to a problem? Please describe.**
Receive "Abfragen des USSD-Codes fehlgeschlagen"

**Describe the solution you'd like**
Don't try to check if phone is in airplane mode

**Describe alternatives you've considered**

**Additional context**

**Comment by mueller-ma** [comment]
WorkManager (the lib used for background tasks) allows to set conditions before the background work is done. It has "internet required", but no "connection for USSD required".

I'd rather try to find a solution for #155 and only display a notification if checking failed for a few times.
