### ISSUE TITLE
Keep timestamp of each 1st amount change 

### ISSUE THREAD

**Issue by markushub** [mueller-ma/PrepaidBalance#170]
**Is your feature request related to a problem? Please describe.**
The real date for the first time when prepaid balance was change is the imported, not the date of last check 

**Describe the solution you'd like**
Keep the last item, don't override date/timestamp  if prepaid balance was not changed. 

**Describe alternatives you've considered**
Temporary add an item, with the same amount, but different date, and remove duplicate later

**Additional context**
usefull app, thank you

**Comment by mueller-ma** [comment]
>  Keep the last item, don't override date/timestamp if prepaid balance was not changed.

Seems like a good idea. Maybe add a "last update" hint to the list, so users know that the app did refresh?

**Comment by markushub** [comment]
It sounds like the perfect solution. So we have both the change timestamp und the last update.

BTW: format is currently time before date

     hh:mm DD.MM.YYYY    (20:45 15.12.2022)

I prefer date  before time

    YYYY-MM-DD hh:mm     (2022-12-15 20:45)

**Comment by mueller-ma** [comment]
The timestamp is based on the locale, so I'd like to keep it as is.

**Comment by markushub** [comment]
Okay keep the timestamp format as it is.

Only add a new item line (with the timestamp) only when prepaid balance was changed. Skip all other items.
