### ISSUE TITLE
same Network, different Provider and USSD

### ISSUE THREAD

**Issue by supervisitor** [mueller-ma/PrepaidBalance#177]
Hi all.

Inside [values-mcc228-mnc002](https://github.com/mueller-ma/PrepaidBalance/tree/main/app/src/main/res/values-mcc228-mnc002)/strings.xml you define Sunrise/Switzerland

I use yallo/Switzerland, and yallo is a subsidiary of Sunrise which use the same Infrastructure (not only the network). So I have the same Provider details:
- MCC: 228
- MNC: 2
... but the USSD to get my balance is not *121#, the correct is *123# for yallo users.

On the other side, from Sim card you fetch the correct Provider name... so when you insert this in you lookup function, you could set this correct by default.

Cheers...

**Comment by mueller-ma** [comment]
There's also another issue: The values-mcc*-mnc* folders set the USSD code based on the primary sim card, which might be a different one than the user selects in the settings.
Maybe I'm going to remove the default USSD code at all.

**Comment by supervisitor** [comment]
... I haven't looked into the source code, but is the USSD determined more often than just for the initial setup?
So I would keep this automatism to determine the USSD included for less technical users. But from the moment the correct USSD is set, I would only read it from the configuration file.

What I would change:
- in the preferences pane I would put the selection of the sim card above the setting of the USSD, so swap the top two settings
- I would extend the automatic determination of the correct USSD to handle all these special cases

all users of you App will love it!  😇

**Comment by supervisitor** [comment]
... but I would think about replacing the many of individual directories with the strings.xml file with USSD inside with a substitution table:
| PLMN | MCC | MNC | Carrier identifier/name | USSD |
| --- | --- | --- | --- | --- |
| 22802 | 228 | 02 | yallo | *123# |
...

and then query them in a simple function flow for setting the correct USSD could look like this:
- Determine number of possible (e)Sim [Result = 0-3 possible].
- 0 = without modem (software installed on tablet without modem) = no prepaid => autoconfiguration end
- Determine number of used (e)Sim [Result = 0-3 possible]
- 0 = Mobile is without SIM = no prepaid => autoconfiguration end
- Set loop start
- Sim0 = no autoconfiguration possible => autoconfiguration end
- query last Sim for PLMN and operator name
- use USSD from substitution table for PLMN and operator name to query account balance [result = nonsense or useful].
- show result that may be useful => autoconfiguration end
- absurd result => switch to the sim before (Sim=Sim-1) and jump to the loop start
- Loop end
- Store USSD in configuration

... from now on read USSD from file only
