### ISSUE TITLE
Recharge reminder - feature request

### ISSUE THREAD

**Issue by supervisitor** [mueller-ma/PrepaidBalance#180]
Some people (like me) have a second prepaid card next to the main card in the mobile for e.g. travel to certain countries. But this card can expire if it is not recharged regularly, no matter how high the balance is, if it is not recharged regularly.
The app knows the last deposit amount and the date. So why not a reminder when the expiration date is coming up. In Preferences pane enable this option and enter the maximum recharge period, e.g. 3 months, one year, two years or an individual number of months; and if this needs to be recharged, a reminder will come 1 month, one week and 1 day before the expiration date.

**Comment by OmlineEditor** [comment]
+1

**Comment by mueller-ma** [comment]
https://github.com/mueller-ma/PrepaidBalance/issues/96#issuecomment-2460571668
