### ISSUE TITLE
Phone number is displayed with decimal places

### ISSUE THREAD

**Issue by kri164** [mueller-ma/PrepaidBalance#188]
**Describe the bug**
Application displays phone numbers as numbers with decimal places. It looks very ugly.
Decimal places are separated with decimal dot or decimal dime, depends on LOCALES settings.

**Screenshots**
![balance-1](https://user-images.githubusercontent.com/52274164/216278827-40b42e9e-927a-4e59-981d-042767d3d6ff.png)
![balance-2](https://user-images.githubusercontent.com/52274164/216278854-6a0e0284-2210-43fc-836a-85fc8b35e7d3.png)

**Device (please complete the following information):**
 - Device: RedMi 9
 - Android version: 11, LineageOS 18.1
 - MCC and MNC (Shown in settings): 
 - App is installed from F-Droid
 - App version: 1.18

**Comment by mueller-ma** [comment]
> Phone number is displayed with decimal places 

The real issue is that the app parses the phone number as balance. Can you post the full USSD response? Feel free to redact your phone number in the response with a dummy phone number (e.g. `123456`).

**Comment by kri164** [comment]
**Text of USSD response:**
Dobry den, aktualni vyse Vaseho kreditu na cisle 12345678 je 300 Kc, z toho  bonusovy kredit je 0 Kc. Platnost bezneho kreditu: 30. 1. 2024 18:18. Vase O2

**Translation to english:**
Hello, the current amount of your credit on 12345678 is 300 Kc, of which the bonus credit is 0 Kc. Expiry date of the standard credit: 30 January 2024 18:18. Your O2

Network: O2, MMC: 230, MNC: 02
USSD code: \*104\*#

![balance-3](https://user-images.githubusercontent.com/52274164/216315640-64ba0a40-8f26-4eb8-b809-9620b745985a.png)


Thank you very much
