### ISSUE TITLE
GitHub release

### ISSUE THREAD

**Issue by xmha97** [mueller-ma/PrepaidBalance#203]
Hi @mueller-ma 
Please upload APK files to GitHub release.
Play Store and F-Droid and VPNs blocked on my country and I can't update this app.
Thanks 🙏

**Comment by mueller-ma** [comment]
Also see  https://github.com/mueller-ma/Coffee/issues/231

**Comment by xmha97** [comment]
Also please upload APK for this project like Coffee:
https://github.com/mueller-ma/Coffee/releases

**Comment by xmha97** [comment]
@mueller-ma 
Please upload the APK file for this project like Coffee:
https://github.com/mueller-ma/Coffee/releases

**Comment by xmha97** [comment]
Thanks 🙏
