### ISSUE TITLE
Problems of formatting the output

### ISSUE THREAD

**Issue by OmlineEditor** [mueller-ma/PrepaidBalance#210]
**Describe the bug**
Formatting the output of the balance moves and does not look beautiful

**To Reproduce**
I change the USSD code and make a request. The numbers are always moving and it all looks terrible.

**Device (please complete the following information):**
 - Device: Redmi Note 7
 - Android version: 10
 - PrepaidBalance v1.20 (F-Droid)

**Screenshots**

![1](https://user-images.githubusercontent.com/13348933/229088853-6c8f11e8-8a3e-4023-9650-b286c2097da3.jpg)
![2](https://user-images.githubusercontent.com/13348933/229088863-0cc1927d-f828-445a-bee5-1589fca439e2.jpg)
![3](https://user-images.githubusercontent.com/13348933/229088864-45ef3b6e-a12d-4901-bd98-39c8e2b4b389.jpg)
![4](https://user-images.githubusercontent.com/13348933/229088868-604ddc5a-c094-497a-91b6-6a1860eb7b94.jpg)
![5](https://user-images.githubusercontent.com/13348933/229088871-e8353d1e-8d56-48a1-915f-e699fcf6da8e.jpg)
![6](https://user-images.githubusercontent.com/13348933/229088874-7bb91f2e-e0dd-4e52-ab8d-6fab3372c7ba.jpg)
![7](https://user-images.githubusercontent.com/13348933/229088877-901d969b-e42e-4025-92b8-f71bb85614d6.jpg)

**Comment by mueller-ma** [comment]
I haven't found a way so far to ensure that the balance view and the diff view have the same width across all rows.

**Comment by OmlineEditor** [comment]
disable the bot so that it does not close tickets

**Comment by mueller-ma** [comment]
The issue is caused by parsing wrong values from the balance. You can remove single invalid values and that should fix the issues.
As I wrote before I haven't found a way to sync the width of values between all rows.

**Comment by OmlineEditor** [comment]
perhaps you can do it like this:
1) use a monospace font
2) store the maximum width of all values ​​(go through all values ​​and look for the maximum)
3) knowing the maximum width, format all fields along the right edge.
