### ISSUE TITLE
Remove the icon app from the widget

### ISSUE THREAD

**Issue by xmha97** [mueller-ma/PrepaidBalance#216]
Please remove the icon app from the widget.

![Screenshot_2023-04-16-12-54-01-333_com.miui.home.jpg](https://user-images.githubusercontent.com/23485114/232289511-f8672cf5-e75c-40f7-bd4d-6a98bc3a90ba.jpg)

**Comment by mueller-ma** [comment]
I'm not sure about this change. I want to ensure the user knows what this number means, so I added the app icon. It doesn't use any extra space, compared to an additional text with "Prepaid balance".

**Comment by xmha97** [comment]
Ok, add app icon before number. (Like Bitcoin widget on picture below)

![ResizedImage20230417_090613.jpg](https://user-images.githubusercontent.com/23485114/232392180-5b870de3-1cff-495c-b737-ca70d4be4eb9.jpg)

**Comment by xmha97** [comment]
Thanks 🙏
Why isn't the app icon transparent?

![Screenshot_2023-04-22-01-30-10-061_com.miui.home.jpg](https://user-images.githubusercontent.com/23485114/233741126-b75ca6cd-fec4-4118-97f9-e6649d3fe9bc.jpg)

**Comment by mueller-ma** [comment]
IMO it looks better the way it currently is.
