### ISSUE TITLE
Failing USSD response is falsely parsed as balance (Vodafone Germany)

### ISSUE THREAD

**Issue by araccaine** [mueller-ma/PrepaidBalance#249]
**Describe the bug**
For Vodafone Germany, sometimes the response for USSD code `*106#` is the following:

> Dieser Service steht auf Grund von Wartungsarbeiten leider erst ab 9 Uhr wieder zur Verfügung.

This simply means that the service is currently under maintenance until 9 o'clock.

**Expected behavior**
PrepaidBalance should not parse this response as valid balance.

**Screenshots**
![IMG_20231105_114205.jpg](https://github.com/mueller-ma/PrepaidBalance/assets/75312500/b83ce729-a3b9-4adb-97f5-621427889f92)

**Comment by araccaine** [comment]
This is slightly related to #182 but simply for another service provider.

**Comment by mueller-ma** [comment]
Fixed in https://github.com/mueller-ma/PrepaidBalance/releases/tag/2.4. You can long-press the old values to delete them.
