### ISSUE TITLE
Another missing parsing of a Vodafone USSD response

### ISSUE THREAD

**Issue by cyclingcat** [mueller-ma/PrepaidBalance#255]
**Describe the bug**
The German Vodafone reseller "Lidl Connect" recently sent a USSD response that includes the service phone number 22922, which is currently misinterpreted as an account balance "22.922,00". See the screenshot:

![Lidl](https://github.com/mueller-ma/PrepaidBalance/assets/32601012/c05242ce-53ba-4013-aac2-b60c04856d5d)

App version 2.3 from F-Droid. (The marked "9,00" at the top of the screen seems to be fixed with v2.4, which is not on F-Droid yet.)

**Device (please complete the following information):**
 - Device: Realme 8 Pro
 - Android version: 13
 - MCC: 262, MNC: 1

This is similar to issue #249.

The cycling cat

**Comment by mueller-ma** [comment]
I thought this is easy to fix, but it seems `String.startsWith` breaks on umlauts...

https://github.com/mueller-ma/PrepaidBalance/pull/256
