### ISSUE TITLE
Polish Plus network support

### ISSUE THREAD

**Issue by konradmb** [mueller-ma/PrepaidBalance#51]
**Describe the bug**
Balance is incorrectly parsed when on Polish Plus network. Instead phone number is shown as balance.

**To Reproduce**
1. Refresh balance

**Expected behavior**
Actual account balance is shown in app.

**Device (please complete the following information):**
 - MCC and MNC (Shown in settings): 260 1

**Additional context**
USSD response: `Aktualny stan konta dla numeru 48123456789: 1,23 PLN. Konto wazne do dnia 01-01-2022 01:02:03.Doladuj PLUSem! `

I've modified source to add this matcher on first place (and it works), but I don't know if it's behaving correctly with other ones:
`Matcher("^(.*?)((\\d)+\\.(\\d){1,2}) PLN(.*?)\$".toRegex(), 2),`

**Comment by mueller-ma** [comment]
I added your regex to the app. It didn't break any unit test, so it should be fine.

**Comment by konradmb** [comment]
Thanks!
