### ISSUE TITLE
Notification limit for used credits in a day

### ISSUE THREAD

**Issue by SimonHeimberg** [mueller-ma/PrepaidBalance#61]
**Is your feature request related to a problem? Please describe.**
Sometimes a data package I buy runs out without me realising it. Then my phone uses credits directly, using them up quickly.

**Describe the solution you'd like**
When I could set a limit for used credits in a certain time (1 day, ...), this could help to see the problem early. (Being able to set the interval of requesting the credit could help even further.)

**Describe alternatives you've considered**
I currently set the limit a bit lower than my balance. I have to adapt this value each time I buy a package or load credits.

**Additional context**
The balance of used credits could be enabled and set in the settings, similar to the (absolute) limit.

**Comment by mueller-ma** [comment]
Sorry for the late reply. This seems like a valid feature request to me, so PRs are welcomed :)
