### ISSUE TITLE
ussd code for Djibouti Telecom is *168#

### ISSUE THREAD

**Issue by SimonHeimberg** [mueller-ma/PrepaidBalance#62]
**Describe the bug**
The ussd code for Djibouti Telecom is *168#.

No problem to set it manually. But you write this shall be reported.

**Device (please complete the following information):**
 - Device: 
 - Android version: 
 - MCC and MNC (Shown in settings): 
MCC: 638
MNC: 1

**Comment by mueller-ma** [comment]
Thanks for reporting.
