### ISSUE TITLE
Add support for Globe Telecom

### ISSUE THREAD

**Issue by huckleberrypie** [mueller-ma/PrepaidBalance#81]
**Describe the bug**
I'd like to see support added for Globe Telecom in the Philippines, please. They use the USSD code *143#.

**Device (please complete the following information):**
 - Device: Realme C3
 - Android version: 12.1
 - MCC and MNC (Shown in settings):
MCC: 515
MNC: 2
Last request failed with code -1

**Comment by mueller-ma** [comment]
`-1` means that the mobile network didn't finish the request. Does `*143#` work when you dial it in the dialer?

**Comment by huckleberrypie** [comment]
> `-1` means that the mobile network didn't finish the request. Does `*143#` work when you dial it in the dialer?

Yes, *143# works when I dial it normally.

**Comment by perzarys** [comment]
@huckleberrypie Just to rule out the obvious here, did you actually enter your code in the app settings? If not, it will just dial a default code which won't work in your case, obviously

**Comment by huckleberrypie** [comment]
> @huckleberrypie Just to rule out the obvious here, did you actually enter your code in the app settings? If not, it will just dial a default code which won't work in your case, obviously

Yes, I did.

**Comment by mueller-ma** [comment]
Did you grant the phone permission?

**Comment by huckleberrypie** [comment]
> Did you grant the phone permission?

Yes, everything seems well accounted for.
![Screenshot_20220516-184954_Permission controller](https://user-images.githubusercontent.com/5564327/168577120-98193d77-1df3-4f11-bd93-763d3041a931.png)

Here's what happens when I query *143# via the phone app itself:
![Screenshot_20220516-185236_Phone Services](https://user-images.githubusercontent.com/5564327/168577563-70a2a196-fc5f-4122-828d-a6e523020651.png)

**Comment by mueller-ma** [comment]
I did some research: The API I use doesn't work for ussd codes that start a session and wait for input:

* https://stackoverflow.com/questions/46519929/interactive-ussd-sessionmulti-step-does-not-work-on-android-8oreo
* "won't fix" in the Google issue tracker :( https://issuetracker.google.com/issues/69251738

Is there any other USSD code that provides the balance?

**Comment by huckleberrypie** [comment]
> I did some research: The API I use doesn't work for ussd codes that start a session and wait for input:
> 
>     * https://stackoverflow.com/questions/46519929/interactive-ussd-sessionmulti-step-does-not-work-on-android-8oreo
> 
>     * "won't fix" in the Google issue tracker :( https://issuetracker.google.com/issues/69251738
> 
> 
> Is there any other USSD code that provides the balance?

Not sure, that's the only way subscribers can check for the prepaid balance. Did you see the screenshot above tho? IDK if it's possible to parse that "BAL 20.9" thing to tell the user they only have 20 pesos left in their account.

**Comment by noriellecruz** [comment]
i think this issue can be solved if the app will use https://github.com/romellfudi/VoIpUSSD for USSD requests

**Comment by huckleberrypie** [comment]
> just to give an update. [@huckleberrypie](https://github.com/huckleberrypie) seems to be on Globe Network. the ussd request will work if it's supplied as multi-step command: `*143*13*1*1#`
> 
> this is the response after running that ussd command: ![Image](https://github.com/user-attachments/assets/df4f3c64-d9ab-43bc-aefa-44f46453bd71)

I'm getting an "Invalid Bookmark" error with that command.
