### ISSUE TITLE
Special USSD string showing multiple sub-balances

### ISSUE THREAD

**Issue by perzarys** [mueller-ma/PrepaidBalance#84]
**Describe the bug**
When you're on "Kaufland mobil", a german prepaid reseller, their USSD strings are a bit out of the norm, to say the least.
The string looks like this:
 
_**Dein Guthaben betraegt: 10,00 EUR Startguthaben, 0,00 EUR Kaufguthaben und 0,01 EUR Geschenkguthaben.**_

So it is split into multiple sub-balances, Startguthaben is the credit you get gifted for joining the carrier, Kaufguthaben is the amount you actually topped up with your own money, and Geschenkguthaben is special credits like a bonus for bringing your old phone number with you.
When there's no Startguthaben and/or Geschenkguthaben left, the respective subsection disappears from the USSD response.
For example, when you received no Geschenkguthaben and only have Startguthaben, it will look like this:

_**Dein Guthaben betraegt: 10,00 EUR Startguthaben und 0,00 EUR Kaufguthaben.**_

Kaufguthaben will always appear in the response.

The app currently only reads the first balance that appears in the string, so the 10,00 EUR. 
I attached a screenshot which shows the situation, and also the toast notification with the USSD string at the bottom.

**To Reproduce**
1. insert Kaufland mobil SIM card
2. dial their USSD code, which is *144#
3. See that the above described string appears

**Expected behavior**
I would expect the app to just sum up all balances it finds in the string.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/104169124/168417313-0dd41e6b-008b-4de6-954a-97f21c2a19a0.png)

**Comment by mueller-ma** [comment]
I'll add an additional response parser for this case.

Can you provide the MNC and MCC? Then I can add the default USSD code for this provider.

**Comment by perzarys** [comment]
> Can you provide the MNC and MCC? Then I can add the default USSD code for this provider.

Sure, sorry I missed that one.
MCC: 262
MNC: 1

**Comment by mueller-ma** [comment]
It has the same codes (MNC and MCC) than Deutsche Telekom, so I cannot add it. The parser issue is fixed.
