### ISSUE TITLE
Scrabbing error.

### ISSUE THREAD

**Issue by Vintic** [mueller-ma/PrepaidBalance#88]
Don't know if I should create new issue or reopen another with same problem: https://github.com/mueller-ma/PrepaidBalance/issues/11

**Describe the bug**
Main function doesnt work. Error appear on extracting data.

**To Reproduce**
1. Turn on your phone
2. Install the app
3. Open app
4. Enter your USSD in app settings: "*133#"
5. "swipe down", 
6. wait, after 5 seconds error message appear: "Failed to receive USSD code".
7. wait, after 1 minute appear system error, like: "Network problem, or wrong MMI code"

**Expected behavior**
See scrabed data, instead of error message.

**Screenshots**
![Screenshot_20220522-082831_Prepaid Balance](https://user-images.githubusercontent.com/15685083/169680302-db44b9d8-bc22-4c16-9a1f-ca7ed1e6998a.jpg)
![Screenshot_20220522-082815_Prepaid Balance](https://user-images.githubusercontent.com/15685083/169680304-a87c564e-dbb2-4e67-bdb2-6ddc5b8a806a.jpg)
![Screenshot_20220522-082728_Prepaid Balance](https://user-images.githubusercontent.com/15685083/169680306-72f825f9-f22c-43df-a98b-34a49ad03f44.jpg)

**Device:**
Phone: Samsung s21+
Android: 12
MCC: 259
MNC: 1

**Additional context**
Last error for V 1.5: "Last request failed to complete"
Last error for previous app version was like: ...-1...

**Comment by mueller-ma** [comment]
Can you dial `*133#` in your dialer and post a screenshot of that?

**Comment by Vintic** [comment]
Uh sorry, forgot about it
![Screenshot_20220523-075505_Phone](https://user-images.githubusercontent.com/15685083/169746251-4e24a506-7aa7-4018-b9b6-d6f865b4f281.jpg)

**Comment by mueller-ma** [comment]
This kind of USSD response cannot be parsed by the Android library I use: https://github.com/mueller-ma/PrepaidBalance/issues/81#issuecomment-1131516634
