### ISSUE TITLE
Invalid ussd code

### ISSUE THREAD

**Issue by audunmg** [mueller-ma/PrepaidBalance#95]
The correct ussd code for my network is `*123*8*2#`

The regex for validation doesn't seem to allow for that.

https://github.com/mueller-ma/PrepaidBalance/blob/b218fbb68e8e71194b5665f1feeec57f7da254be/app/src/main/java/com/github/muellerma/prepaidbalance/utils/ExtensionFunctions.kt#L25

Additionally, and I'm not sure how to fix this, but i tried running a normal ussd code in the app, but it says "failed to request ussd code". It has phone permission, so I don't know what's wrong.

I'd be happy to collect more information to fix this.

It's on a Samsung note 20 with stock firmware, if that helps.

Thanks for making this otherwise nice app!

**Comment by mueller-ma** [comment]
Version 1.7 should be live on F-Droid in a few days with this fix.
