### ISSUE TITLE
support 2 sim cards

### ISSUE THREAD

**Issue by OmlineEditor** [mueller-ma/PrepaidBalance#96]
**Is your feature request related to a problem? Please describe.**
the phone has 2 different SIM cards.  there are different USSD balance request codes for cards.

**Describe the solution you'd like**
add the ability to work with two different SIM cards. specify different USSD codes.

**Comment by OmlineEditor** [comment]
in the phone settings, it is possible to specify the color and name of the SIM card. please take this into account and specify it in the settings and the balance display.

**Comment by OmlineEditor** [comment]
in the phone settings, it is possible to specify the color and name of the SIM card. please take this into account and specify it in the settings and the balance display.

**Comment by adonetgithub** [comment]
I have the same Problem. I have one prepaid sim card on which I want to use the USSD check and the other sim card does not support that. Could you at the possibility to select the sim card that is used for the USSD check?

**Comment by adonetgithub** [comment]
> I have the same Problem. I have one prepaid sim card on which I want to use the USSD check and the other sim card does not support that. Could you at the possibility to select the sim card that is used for the USSD check?

Sometimes the app uses the right sim card, and works fine, but other times it does not. Can you please add a feature to choose the right sim card for balance checking?

**Comment by Devendra34** [comment]
Hi @mueller-ma, 
I'm interested. Just to clear the requirements once again, we need an option to select a sim card by the user to proceed with sending USSD request.
Would you please assign it to me?
Thanks!

**Comment by mueller-ma** [comment]
In this issue I'd track _true_ multi sim support, i.e. set different USSD codes for each sim card. You can implement #124 by adding a simple setting to select one sim card.

**Comment by Devendra34** [comment]
Sure @mueller-ma,
In that case, please assign #124 to me. Let me work on the same there.

**Comment by OmlineEditor** [comment]
now you can request data from different sim cards, you have made it possible to find out the balance of different sim cards. Make it possible to monitor several parameters on different SIM cards at the same time. I would like to monitor the balance on two SIM cards and the number of SMS messages on one of the cards and the volume of Internet traffic on the second SIM card.

![sim](https://user-images.githubusercontent.com/13348933/204800624-91e0517b-d902-4435-bec0-69bc0a1ab127.jpg)

**Comment by OmlineEditor** [comment]
In the settings you also need to specify the name of the SIM card for the widget https://github.com/mueller-ma/PrepaidBalance/issues/164 a shorter name and units of measurement

**Comment by OmlineEditor** [comment]
remove the bot that closes tickets, it hinders development and closes useful tickets

**Comment by oliver** [comment]
For the record: I have now used [Shelter](https://f-droid.org/de/packages/net.typeblog.shelter/) to install the Prepaid Balance app a second time on my phone, into a "work profile". And that second installation now checks the balance on my second SIM card.

In manual testing it worked fine. I'll see in the future whether notifications for low balance work as well.

One hitch is that for the second SIM card the USSD code of the first card was used (I guess that's the problem that was described at https://github.com/mueller-ma/PrepaidBalance/issues/124#issuecomment-1275712011). I have therefore googled for the correct USSD code for my second carrier and manually configured it.

Thanks for creating this app! For me it made a small but annoying task (remembering to recharge) just disappear \o/ .

**Comment by mueller-ma** [comment]
> it hinders development 

Well, I don't have the time to implement this on my own (see Readme: "I probably won't add new major features on my own") and looking at https://github.com/mueller-ma/PrepaidBalance/graphs/contributors commits other users are mostly fixes and small improvements. So I don't agree that it hinders development.
For now I'd close this issue as it raises hope for users that it will be implemented.
