### ISSUE TITLE
showing statistics for the month and year

### ISSUE THREAD

**Issue by OmlineEditor** [mueller-ma/PrepaidBalance#98]
**Is your feature request related to a problem? Please describe.**
I need to know the expenses for the month and year

**Describe the solution you'd like**
I ask you to make it possible to visually view the statistics of spending for the month and for the year. It is advisable to choose dates and years when to view statistics. the simplest option is to show in the form of a graph the costs by month for the last whole year for 12 months. And be able to choose the year to view.
the red column is the expense, the green one is the arrival of money this month.

![expm](https://user-images.githubusercontent.com/13348933/174632512-857750db-f099-4a13-a47f-08800106c4c8.png)

**Comment by AmartyaSingh97** [comment]
Is this issue still open for hacktoberfest?

**Comment by mueller-ma** [comment]
Yes, it's still open.

**Comment by OmlineEditor** [comment]
remove the robot so that it does not close tickets

**Comment by mueller-ma** [comment]
It's quite a large change compared to the current code base. I don't have the (time) resources to implement this feature. If someone wants to implement it, I'll review it.
But if that doesn't happen, I'd like to close issues to 1. keep the issue list clean and 2. to not raise expectations for someone who sees the open feature request.

**Comment by OmlineEditor** [comment]
please do not close the ticket. an open ticket will help other users with ideas and maybe someone will want to implement the function
